name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Build application for static export
      run: |
        # Create a temporary Next.js config for static export
        cp next.config.ts next.config.ts.backup
        cat > next.config.ts << 'EOF'
        import type { NextConfig } from "next";

        const nextConfig: NextConfig = {
          output: 'export',
          trailingSlash: true,
          images: {
            unoptimized: true
          },
          basePath: '/pomera-new-hahmed',
          assetPrefix: '/pomera-new-hahmed',
          eslint: {
            ignoreDuringBuilds: true,
          },
          typescript: {
            ignoreBuildErrors: true,
          },
        };

        export default nextConfig;
        EOF
        
        # Build the application
        npm run build
        
        # Restore original config
        mv next.config.ts.backup next.config.ts
      env:
        NODE_ENV: production
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        cname: # Add your custom domain here if you have one
